spring:
  application:
    name: funds-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/funds_db}
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    url: /openapi/openapi.yaml
    disable-swagger-default-url: true